const C = {
  bg:"#f8fafc",surface:"#ffffff",dark:"#0f172a",darkMid:"#1e3a5f",
  muted:"#64748b",subtle:"#94a3b8",border:"#e2e8f0",faint:"#f1f5f9",
  red:"#E8400C",blue:"#0C6EE8",purple:"#8B0CE8",green:"#16a34a",
  amber:"#ca8a04",orange:"#c2410c",
};

const COMPETITORS = ["All","Noon","Talabat","Shein","Temu","Trendyol","Careem","Keeta","Jahiz","Jarir","Jumia","Hepsiburada","Getir","Migros","Checkers","Takealot"];

const INSIGHTS = [
  {id:1,category:"Earnings & Results",categoryColor:"#0C6EE8",competitor:"Talabat",headline:"Talabat Q1 2026: GMV up 18% to $2.7B, raises full-year net income guidance to $300-330M",synthesis:"Talabat reported Q1 2026 results on 12 May, beating guidance. GMV grew 18% YoY to $2.7B, with GCC up 12% and non-GCC (primarily Egypt) surging 52%. Revenue rose 22% to $1.05B. Adjusted EBITDA of $130M. Net income $87M. Free cash flow $104M. Full-year net income forecast raised by $20M, citing stronger Ramadan trading. Talabat Pro subscribers hit 49% of GMV in March 2026, up from 32% a year prior.",sources:[{name:"Gulf News",tier:1,url:"https://gulfnews.com/business/retail/talabat-sees-higher-income-in-2026-as-spike-in-orders-drive-strong-q1-growth-1.500537728",date:"12 May 2026",paywall:false},{name:"Zawya",tier:1,url:"https://www.tradingview.com/news/reuters.com,2026-05-12:newsml_ZawbRLr9G:0-zawya-talabat-delivers-strong-q1-2026-performance-advances-strategic-investments-and-increases-guidance/",date:"12 May 2026",paywall:false}],corroborated:true,relevanceScore:98},
  {id:2,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Talabat",headline:"Talabat opens MENA's largest AI-powered fulfilment hub in Cairo — 27,000 sqm, 1M items/day",synthesis:"Talabat Egypt inaugurated MENA's largest quick-commerce fulfilment centre on 28 April 2026 at the Yanmu East Logistics Complex, Cairo-Suez Road. Spanning 27,000 sqm with capacity for 1 million items daily, it supports Talabat Mart across 12 Egyptian cities with plans to expand to 17. Deploys proprietary AI for demand forecasting and inventory optimisation. Egyptian ministers of Communications, Finance, Investment and Industry attended.",sources:[{name:"Daily News Egypt",tier:1,url:"https://www.dailynewsegypt.com/2026/04/28/egypt-launches-menas-largest-ai-powered-quick-commerce-fulfilment-hub-for-talabat/",date:"28 Apr 2026",paywall:false},{name:"Retail ME",tier:2,url:"https://www.retailmanagementmiddleeast.com/news/talabat-egypt-opens-menas-largest-e-commerce-hub",date:"28 Apr 2026",paywall:false}],corroborated:true,relevanceScore:96},
  {id:3,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Noon",headline:"Noon confirms dual UAE-Saudi IPO within 24 months at ~$10B valuation; autonomous delivery pilots underway",synthesis:"Noon founder Mohamed Alabbar confirmed to the FT the company is almost profitable and targeting a dual listing on UAE and Saudi exchanges within two years. Valued at ~$10B after raising $2.7B since 2016 PIF-backed launch. 2024 GMV estimated at $5-6B (Redseer). Plans to halve its 40,000-strong delivery workforce by 2027 through autonomous vehicles.",sources:[{name:"Khaleej Times",tier:1,url:"https://www.khaleejtimes.com/uae/noon-ipo-dual-listing-saudi-plans",date:"30 Apr 2026",paywall:false},{name:"The National",tier:1,url:"https://www.thenationalnews.com/business/markets/2026/01/02/middle-east-ipos-to-bounce-back-in-2026-after-slump/",date:"2 Jan 2026",paywall:false}],corroborated:true,relevanceScore:94},
  {id:4,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Trendyol",headline:"Trendyol surpasses $1B GMV in Gulf, opens Saudi warehouse, targets 50% international revenue before IPO",synthesis:"Trendyol exceeded $1B GMV in the Gulf with 3M active shoppers and 8M+ app downloads in GCC. Expanded from one UAE warehouse to a second facility in Saudi Arabia, employing 500+ staff. Daily GCC orders reached 200,000. CEO targets 50% international revenue before planned IPO by 2030. Also announced $500M 48MW data centre in Ankara with UAE-based Castle Investments, due Q3 2026.",sources:[{name:"The National",tier:1,url:"https://www.thenationalnews.com/future/technology/2024/10/16/trendyol-launches-turkeys-first-llm-and-accelerates-expansion-in-the-gulf/",date:"Oct 2024",paywall:false},{name:"DCD",tier:2,url:"https://www.datacenterdynamics.com/en/news/turkeys-trendyol-to-build-48mw-data-center-in-ankara/",date:"31 Mar 2026",paywall:false}],corroborated:true,relevanceScore:91},
  {id:5,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Keeta",headline:"Keeta (Meituan) expands to Riyadh with SR1B investment, becomes third-largest food delivery platform in KSA",synthesis:"Keeta, Meituan's international subsidiary, launched in Riyadh with SR1 billion ($266.6M) investment backing Vision 2030. Within four months, it became the third-largest food delivery platform in Saudi Arabia, onboarding 7,000+ restaurants and 10,000+ riders. Three-year plan includes UAE, Qatar, Kuwait, Oman and Bahrain.",sources:[{name:"Arab News",tier:1,url:"https://arabnews.com/node/2574628/amp",date:"Oct 2024",paywall:false},{name:"Rest of World",tier:1,url:"https://restofworld.org/2025/delivery-app-keeta-hungerstation-saudi-arabia/",date:"Mar 2025",paywall:false}],corroborated:true,relevanceScore:89},
  {id:6,category:"Regulatory",categoryColor:"#8B0CE8",competitor:"Shein",headline:"Alshaya Group calls for regulation of Shein and Temu at UAE-Kuwait Economic Forum",synthesis:"Alshaya Group Executive Chairman called for legislation to level the playing field between e-commerce platforms and traditional retail at the UAE-Kuwait Economic Forum in Dubai. He argued Shein and Temu generate profits transferred to China without contributing to local economies through hiring nationals, paying municipal fees, or leasing retail space.",sources:[{name:"Argaam",tier:2,url:"https://www.argaam.com/en/article/articledetail/id/1877018",date:"2 Feb 2026",paywall:false}],corroborated:false,relevanceScore:82},
  {id:7,category:"Supply Chain",categoryColor:"#0891b2",competitor:"Shein",headline:"Amazon, Temu and Shein extend Middle East delivery windows by up to 10 days as conflict disrupts shipping",synthesis:"Regional conflict from late February 2026 forced major platforms to revise delivery estimates. Temu extended windows from 7-15 to 6-20 days; Shein from 5-8 to 8-10 days; Amazon to 35-45 days for some products. CMA CGM introduced an emergency conflict surcharge and Hapag-Lloyd a War Risk Surcharge.",sources:[{name:"Bloomberg",tier:1,url:"https://worldef.com/2026/03/09/amazon-temu-middle-east-shipping-delays/",date:"9 Mar 2026",paywall:true},{name:"The Citizen",tier:2,url:"https://www.citizen.co.za/business/delays-shipments-temu-shein-amazon-middle-east/",date:"3 Mar 2026",paywall:false}],corroborated:true,relevanceScore:93},
  {id:8,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Shein",headline:"Shein launches semi-managed seller model in Middle East, partners with Chalhoub Group and Apparel Group",synthesis:"Shein launched a semi-managed business model for its Middle East platform on 30 April. Two routes for brand partners: retail model and marketplace model. Key partners include Chalhoub Group, Apparel Group, and Maybelline. Shein has operated a Dubai office since 2016; the Middle East is among its highest-margin regions.",sources:[{name:"PR Newswire",tier:2,url:"https://www.prnewswire.com/ae/news-releases/shein-middle-east-shines-spotlight-on-diverse-partnership-models-for-brand-growth-and-acceleration-302676317.html",date:"2 Feb 2026",paywall:false}],corroborated:false,relevanceScore:85},
  {id:9,category:"Market Data",categoryColor:"#0891b2",competitor:null,headline:"UAE quick-commerce market hits $187M in 2026 — 54.8% of orders delivered in under 30 minutes",synthesis:"The UAE quick-commerce market reached $187.41M in 2026, with 54.8% of orders now delivered in under 30 minutes. Talabat, Noon Minutes, Careem, and Carrefour dominate. Market projected to reach $1.86B by 2029. UAE Cashless 2026 initiative targets 90% digital transactions this year.",sources:[{name:"GlobeNewswire",tier:2,url:"https://www.globenewswire.com/news-release/2026/04/17/3276054/28124/en/United-Arab-Emirates-Quick-Commerce-Databook-Report-2026-Market-to-Reach-1-86-Billion-by-2029-Talabat-Noon-and-Careem-Lead-as-Carrefour-Leverages-Localized-Retail-Hubs-for-Same-Hou.html",date:"17 Apr 2026",paywall:false}],corroborated:false,relevanceScore:74},
  {id:10,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Careem",headline:"Careem Pay processes $2B+ annualised volume; EBITDA positive in FY2025; IPO on ADX or DFM possible by late 2026",synthesis:"Careem Pay processed over $2B in annualised transaction volume by early 2026, with monthly active payer share at ~18%. Careem Plus subscription at 5M monthly active members generates ~$150M ARR. Group-adjusted EBITDA turned positive in FY2025 at $48M. A $400M strategic investment from e& funds platform decoupling from Uber's stack. Gross transaction value in 2025 was $3.2B.",sources:[{name:"Business Model Canvas",tier:2,url:"https://businessmodelcanvastemplate.com/products/careem-swot-analysis",date:"2026",paywall:false}],corroborated:false,relevanceScore:72},
  {id:11,category:"Market Data",categoryColor:"#0891b2",competitor:null,headline:"GCC quick-commerce on track for $4.9B by 2029 — Talabat, Careem, and Breadfast lead regional expansion",synthesis:"Africa and Middle East quick commerce forecast to grow 8.9% annually through 2029, reaching $4.9B from $3.2B in 2024. In GCC, Talabat, Careem, and large grocers dominate. Dark-store density and loyalty subscriptions are primary competitive differentiators.",sources:[{name:"GlobeNewswire",tier:2,url:"https://www.globenewswire.com/news-release/2026/04/21/3277639/0/en/Africa-and-Middle-East-Quick-Commerce-Report-2026-Market-to-Reach-4-9-Billion-by-2029-Talabat-Careem-and-Breadfast-Lead-Growth-as-Super-Apps-and-Vertical-Integration-Drive-Regional.html",date:"21 Apr 2026",paywall:false}],corroborated:false,relevanceScore:68},
  {id:12,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Takealot",headline:"Takealot opens marketplace to Chinese sellers to counter Temu and Shein on price",synthesis:"South Africa's dominant e-commerce platform Takealot expanded its pool of international sellers including Chinese merchants to compete with Temu and Shein on price. Customer complaints about long delivery times and quality have increased. Last reported full-year revenue (March 2025) was R14.95B ($872M), up 15%, but barely profitable.",sources:[{name:"TechCabal",tier:2,url:"https://techcabal.com/2026/04/15/techcabal-daily-takealot-and-wait-for-delivery/",date:"15 Apr 2026",paywall:false}],corroborated:false,relevanceScore:65},
  {id:13,category:"Funding & M&A",categoryColor:"#0C6EE8",competitor:"Jumia",headline:"Jumia reports 34% revenue surge in Q4 2025, advances toward EBITDA breakeven by late 2026",synthesis:"Jumia reported a 34% revenue surge in Q4 2025 and is advancing toward adjusted EBITDA breakeven by late 2026. Generated $641.9M in GMV in 2024. Exited South Africa and Tunisia in October 2024 to focus on faster-growing West and East African markets. Targeting Egypt and North Africa as growth vectors.",sources:[{name:"Jumia Group",tier:2,url:"https://group.jumia.com/",date:"8 May 2026",paywall:false}],corroborated:false,relevanceScore:71},
  {id:14,category:"Market Data",categoryColor:"#0891b2",competitor:null,headline:"Saudi e-commerce market: $21.3B in 2024, 13% CAGR to $56.6B by 2032 — electronic payments hit 79% of retail",synthesis:"Saudi Arabia's e-commerce market was valued at $21.3B in 2024 and is projected to reach $56.6B by 2032 at 13% CAGR. Electronic payments accounted for 79% of all retail transactions in 2024, exceeding the 70% target set for 2025. SAMA launched Google Pay and agreed to accept Alipay+ by 2026.",sources:[{name:"Verified Market Research",tier:2,url:"https://www.verifiedmarketresearch.com/product/saudi-arabia-e-commerce-market/",date:"Oct 2025",paywall:false}],corroborated:false,relevanceScore:77},
  {id:15,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Noon",headline:"Noon raises $500M led by PIF, earmarks funds for autonomous delivery and logistics AI ahead of IPO",synthesis:"Noon completed a $500M funding round led by Saudi Arabia's Public Investment Fund and founder Mohamed Alabbar. Capital earmarked for autonomous delivery vehicle pilots, AI-driven logistics upgrades, and the dual UAE-Saudi listing plan. Noon currently has over 20 million monthly active users across KSA, UAE, and Egypt.",sources:[{name:"Seetao",tier:2,url:"https://www.seetaoe.com/details/255150.html",date:"Dec 2025",paywall:false}],corroborated:false,relevanceScore:76},
  {id:16,category:"Market Data",categoryColor:"#0891b2",competitor:null,headline:"Turkey e-commerce hits $115B in 2025 — Trendyol ranks #3 globally in Fast Fashion, ahead of Zara and H&M",synthesis:"Turkey's total e-commerce volume reached $115.43B in 2025, up 52.2% year-on-year, representing 19.3% of total trade and 6.9% of GDP. Q1 2026 Cloudflare Radar data shows Trendyol's app ranks #3 globally in Fast Fashion, ahead of Zara, ASOS, and Uniqlo.",sources:[{name:"TechnologyChecker",tier:2,url:"https://technologychecker.io/blog/ecommerce-turkey-statistics",date:"May 2026",paywall:false}],corroborated:false,relevanceScore:66},
  {id:17,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Talabat",headline:"Talabat Pro hits 49% of GMV — Everyday App strategy reshaping MENA super-app competition",synthesis:"Talabat Pro subscription accounted for 49% of GMV in March 2026, up from 32% a year earlier. Talabat is investing $120M in 2026 across expanding Talabat Mart store density, strengthening Pro with ride-hailing and content streaming partner benefits, and building new retail offerings.",sources:[{name:"Investing.com",tier:2,url:"https://www.investing.com/news/company-news/talabat-q1-2026-slides-raises-guidance-amid-18-gmv-growth-93CH-4681127",date:"12 May 2026",paywall:false}],corroborated:false,relevanceScore:88},
  {id:18,category:"Regulatory",categoryColor:"#8B0CE8",competitor:null,headline:"Turkey abolishes simplified B2C customs for foreign parcels — AliExpress and cross-border platforms impacted",synthesis:"Presidential Decree No. 10813, effective January 2026, abolished simplified customs entries for B2C imports in Turkey, extending clearance times for AliExpress and other foreign sellers. Directly benefits domestic players Trendyol and Hepsiburada. Watch for similar regulatory moves in GCC.",sources:[{name:"Mordor Intelligence",tier:2,url:"https://www.mordorintelligence.com/industry-reports/turkey-ecommerce-market",date:"Feb 2026",paywall:false}],corroborated:false,relevanceScore:73},
  {id:19,category:"Market Data",categoryColor:"#0891b2",competitor:null,headline:"Middle East e-commerce projected to reach $12.3T by 2034 at 19.89% CAGR — Egypt fastest growing market",synthesis:"IMARC Group projects the Middle East e-commerce market to reach $12,293.9B by 2034 at 19.89% CAGR, with Egypt emerging as the fastest-growing individual market. Egypt's 105M-person consumer base at ~8% e-commerce penetration represents the largest untapped opportunity in MEATR.",sources:[{name:"IMARC Group",tier:2,url:"https://www.openpr.com/news/4502557/middle-east-e-commerce-market-size-to-hit-usd-12-293-9-billion",date:"May 2026",paywall:false}],corroborated:false,relevanceScore:70},
  {id:20,category:"Funding & M&A",categoryColor:"#0C6EE8",competitor:"Noon",headline:"Saudi delivery IPO pipeline: Ninja targets $1B Tadawul listing, Mr Mandoob valuation surpasses $213M",synthesis:"Ninja, a Saudi last-mile delivery platform, is lining up Citigroup, Goldman Sachs, Riyad Capital and UBS for a $1B Tadawul IPO in late 2026 or early 2027. Mr Mandoob, serving 14M+ users, is preparing for a Nomu listing after its valuation surpassed $213M.",sources:[{name:"Enterprise AM",tier:2,url:"https://enterpriseam.com/menaplus/2026/05/13/saudi-firms-are-lining-up-to-ipo-while-uae-and-egyptian-outfits-strike-more-cautious-notes/",date:"13 May 2026",paywall:false}],corroborated:false,relevanceScore:78},
  {id:21,category:"Competitor Moves",categoryColor:"#E8400C",competitor:"Trendyol",headline:"Trendyol-Baykar-Ant International-ADQ fintech MoU: payments, loans and insurance for MENA sellers",synthesis:"Trendyol, Baykar, Ant International and Abu Dhabi's ADQ signed an MoU to develop a joint fintech platform in Turkey offering payments, deposits, loans, insurance and investment products. ADQ's involvement signals UAE sovereign capital backing a Turkish e-commerce fintech play.",sources:[{name:"FinTech Weekly",tier:2,url:"https://www.fintechweekly.com/magazine/articles/trendyol-baykar-ant-adq-fintech-venture-turkey",date:"Jul 2025",paywall:false}],corroborated:false,relevanceScore:69},
];

const INITIAL_TAGS = [
  {id:1,label:"Saudi last-mile logistics",active:true,priority:1},
  {id:2,label:"BNPL penetration",active:true,priority:2},
  {id:3,label:"Chinese platform expansion",active:true,priority:3},
  {id:4,label:"Egypt market entry",active:true,priority:4},
  {id:5,label:"Marketplace regulation",active:false,priority:5},
];

const TRENDS = {
  weekly:{period:"1 May – 16 May 2026",readMins:5,storiesAnalysed:34,
    summary:"Talabat dominates with Q1 2026 results (GMV up 18% to $2.7B, 12 May) and its Cairo hub opening (28 April, 27,000 sqm, 1M items/day). Noon confirmed its dual UAE-Saudi IPO timeline. Regional conflict disrupted cross-border shipping for Shein, Temu and Amazon, with delivery windows extending by up to 10 days. Saudi delivery IPO pipeline is building — Ninja is eyeing a $1B Tadawul listing.",
    insights:[
      {id:"w1",category:"Earnings & Results",categoryColor:"#0C6EE8",headline:"Talabat Q1 2026: GMV up 18% to $2.7B — Egypt non-GCC segment surges 52%",markets:["UAE","KSA","Egypt"],competitor:"Talabat",corroborated:true,sections:[{theme:"Results",body:"Talabat Q1 2026 GMV grew 18% YoY to $2.7B. Revenue rose 22% to $1.05B. GCC up 12%, non-GCC (primarily Egypt) up 52%. Net income $87M. Free cash flow $104M. Full-year net income guidance raised by $20M to $300-330M."},{theme:"Strategic signal",body:"Talabat Pro accounted for 49% of GMV in March 2026, up from 32% a year earlier. The Everyday App investment of $120M — split across grocery density, Pro subscription, and new retail — is showing clear traction. Multi-vertical customer share rose 4pp YoY to 76%."}],sources:[{name:"Gulf News",tier:1,url:"https://gulfnews.com/business/retail/talabat-sees-higher-income-in-2026-as-spike-in-orders-drive-strong-q1-growth-1.500537728",date:"12 May 2026",paywall:false}]},
      {id:"w2",category:"Competitor Moves",categoryColor:"#E8400C",headline:"Noon confirms dual IPO within 24 months; $500M raised, autonomous delivery in testing",markets:["UAE","KSA"],competitor:"Noon",corroborated:true,sections:[{theme:"IPO trajectory",body:"Noon founder Mohamed Alabbar confirmed a dual UAE-Saudi listing within two years, valuing the company at ~$10B. The company raised $500M led by PIF. Profitability is the gating condition before listing."},{theme:"Cost strategy",body:"Noon is piloting autonomous delivery vans and three-wheeled vehicles, leased rather than purchased. Alabbar targets halving the 40,000-strong delivery workforce by 2027."}],sources:[{name:"Khaleej Times",tier:1,url:"https://www.khaleejtimes.com/uae/noon-ipo-dual-listing-saudi-plans",date:"30 Apr 2026",paywall:false}]},
      {id:"w3",category:"Supply Chain",categoryColor:"#0891b2",headline:"Regional conflict extends delivery windows by up to 10 days for Shein, Temu and Amazon",markets:["UAE","KSA","Egypt"],competitor:"Shein",corroborated:true,sections:[{theme:"What happened",body:"Escalating regional conflict from late February 2026 forced major platforms to revise delivery estimates across the Middle East. Temu extended delivery windows from 7-15 to 6-20 days; Shein from 5-8 to 8-10 days; Amazon to 35-45 days for some products. CMA CGM introduced an emergency conflict surcharge and Hapag-Lloyd a War Risk Surcharge."},{theme:"Strategic implication",body:"Chinese merchants on all three platforms temporarily paused new inventory shipments from China to MENA. Local fulfilment infrastructure such as Talabat's Cairo hub and Keeta's Saudi warehouses proved its value during this period."}],sources:[{name:"Bloomberg",tier:1,url:"https://worldef.com/2026/03/09/amazon-temu-middle-east-shipping-delays/",date:"9 Mar 2026",paywall:true}]},
      {id:"w4",category:"Funding & M&A",categoryColor:"#0C6EE8",headline:"Saudi delivery IPO pipeline builds: Ninja targets $1B Tadawul listing",markets:["KSA"],competitor:"Noon",corroborated:false,sections:[{theme:"The pipeline",body:"Ninja, a Saudi last-mile delivery platform, is lining up Citigroup, Goldman Sachs, Riyad Capital and UBS for a $1B Tadawul IPO in late 2026 or early 2027. Mr Mandoob, serving 14M+ users, is preparing for a Nomu listing after its valuation surpassed $213M. Both represent the first public capital-markets test of Saudi logistics unit economics."}],sources:[{name:"Enterprise AM",tier:2,url:"https://enterpriseam.com/menaplus/2026/05/13/saudi-firms-are-lining-up-to-ipo-while-uae-and-egyptian-outfits-strike-more-cautious-notes/",date:"13 May 2026",paywall:false}]},
    ]},
  monthly:{period:"April – May 2026",readMins:8,storiesAnalysed:112,
    summary:"April and May confirmed two structural shifts: Chinese and Turkish platforms are moving from cross-border testing to local infrastructure investment, and the MENA super-app race is intensifying with Talabat, Careem, and Noon all competing for the everyday app position. The regional conflict disrupted cross-border supply chains but accelerated eat-at-home demand. Trendyol exceeded $1B GMV in the Gulf. Shein launched its semi-managed seller model across MENA.",
    insights:[
      {id:"m1",category:"Competitor Moves",categoryColor:"#E8400C",headline:"Chinese and Turkish platform localisation: from testing to infrastructure",markets:["UAE","KSA","Egypt","Turkey"],competitor:"Trendyol",corroborated:true,sections:[{theme:"The pattern",body:"Three separate infrastructure moves in April-May signal a pivot by non-Amazon platforms. Shein opened a semi-managed seller model (30 April). Trendyol surpassed $1B Gulf GMV with two warehouses in UAE and KSA. Keeta (Meituan) committed SR1B ($266.6M) to Saudi Arabia."},{theme:"What changes for Amazon",body:"Amazon's competitive moat in MENA has rested on delivery speed, seller breadth, and customer trust. Speed is now under attack from multiple directions simultaneously. Trendyol's 200,000 daily GCC orders and Keeta's price-disruption playbook are the two most credible new pressures."}],sources:[{name:"The National",tier:1,url:"https://www.thenationalnews.com/future/technology/2024/10/16/trendyol-launches-turkeys-first-llm-and-accelerates-expansion-in-the-gulf/",date:"Oct 2024",paywall:false}]},
      {id:"m2",category:"Super App",categoryColor:"#7c3aed",headline:"Talabat vs Careem: the MENA everyday app race is intensifying",markets:["UAE","KSA","Egypt"],competitor:"Talabat",corroborated:true,sections:[{theme:"Talabat's position",body:"Talabat Pro at 49% of GMV (March 2026) and $120M investment in 2026 confirm the Everyday App strategy is working. Multi-vertical customers now represent 76% of GMV. The Cairo hub (27,000 sqm, 1M items/day) cements Egypt as a second home market."},{theme:"Careem's counter",body:"Careem Pay processed $2B+ annualised volume. With e&'s $400M investment and group EBITDA turning positive in FY2025 ($48M), Careem is the only platform with a credible super-app infrastructure across ride-hailing, payments, and delivery simultaneously."}],sources:[{name:"Gulf News",tier:1,url:"https://gulfnews.com/business/retail/talabat-sees-higher-income-in-2026-as-spike-in-orders-drive-strong-q1-growth-1.500537728",date:"12 May 2026",paywall:false}]},
      {id:"m3",category:"Regulatory",categoryColor:"#8B0CE8",headline:"Alshaya calls for regulation of Shein and Temu — GCC incumbents pushing back",markets:["UAE","KSA"],competitor:"Shein",corroborated:false,sections:[{theme:"The call",body:"Alshaya Group Executive Chairman called for legislation to level the playing field between e-commerce platforms and traditional retail at the UAE-Kuwait Economic Forum in Dubai. He argued Shein and Temu generate profits transferred to China without contributing to local economies."},{theme:"Why it matters",body:"This is the most senior voice from traditional MENA retail calling for regulation. It mirrors debates in Europe around the EU Digital Services Act and Turkey's January 2026 customs decree. Watch for GCC government response in H2 2026."}],sources:[{name:"Argaam",tier:2,url:"https://www.argaam.com/en/article/articledetail/id/1877018",date:"2 Feb 2026",paywall:false}]},
      {id:"m4",category:"Market Data",categoryColor:"#0891b2",headline:"UAE quick-commerce hits $187M; 54.8% of orders under 30 minutes",markets:["UAE"],competitor:null,corroborated:false,sections:[{theme:"Market snapshot",body:"UAE quick-commerce reached $187.41M in 2026, with 54.8% of orders delivered in under 30 minutes. Talabat, Noon Minutes, Careem, and Carrefour dominate. The UAE's Cashless 2026 initiative targets 90% digital transactions this year. Market projected to reach $1.86B by 2029."}],sources:[{name:"GlobeNewswire",tier:2,url:"https://www.globenewswire.com/news-release/2026/04/17/3276054/28124/en/United-Arab-Emirates-Quick-Commerce-Databook-Report-2026-Market-to-Reach-1-86-Billion-by-2029-Talabat-Noon-and-Careem-Lead-as-Carrefour-Leverages-Localized-Retail-Hubs-for-Same-Hou.html",date:"17 Apr 2026",paywall:false}]},
    ]},
  quarterly:{period:"Q1-Q2 2026 (Jan – May)",readMins:12,storiesAnalysed:287,
    summary:"The first half of 2026 is defined by three converging forces: non-Amazon platforms deploying significant capital into MEATR infrastructure; the MENA platform economy entering a public-markets phase with Noon, Careem, Ninja and Mr Mandoob all moving toward listings; and the regional conflict disrupting cross-border supply chains while accelerating local fulfilment investment. The competitive landscape Amazon faces in H2 2026 is structurally more contested than at any point since Amazon.ae launched in 2019.",
    insights:[
      {id:"q1",category:"Strategic Shift",categoryColor:"#7c3aed",headline:"The MEATR infrastructure race: non-Amazon platforms deploying capital at unprecedented scale",markets:["UAE","KSA","Egypt","Turkey"],competitor:"Trendyol",corroborated:true,sections:[{theme:"Scale of investment",body:"Aggregating Q1-Q2 2026 commitments: Trendyol $1B+ Gulf GMV with two warehouses; Keeta SR1B ($266.6M) Saudi investment; Talabat $120M 2026 investment plan including Cairo hub; Noon $500M raise earmarked for logistics AI and autonomous delivery; Careem $400M from e&. Conservative total of new capital committed to MEATR e-commerce infrastructure in H1 2026: over $2B."},{theme:"Amazon's position",body:"Amazon's incumbency advantage remains intact but is no longer a moat. The critical metric to watch in H2 2026 is Prime membership retention in UAE and KSA as delivery speed parity approaches."},{theme:"What to watch in H2",body:"Trendyol's Egypt push; Keeta's UAE entry (planned); Noon's profitability milestone; Careem IPO timing; whether ZATCA marketplace VAT guidance is finalised. Any two materialising in the same quarter would signal structural acceleration."}],sources:[{name:"Khaleej Times",tier:1,url:"https://www.khaleejtimes.com/uae/noon-ipo-dual-listing-saudi-plans",date:"30 Apr 2026",paywall:false}]},
      {id:"q2",category:"IPO Pipeline",categoryColor:"#0C6EE8",headline:"MENA platform economy entering public markets: Noon, Careem, Ninja, Mr Mandoob all moving toward listings",markets:["UAE","KSA"],competitor:"Noon",corroborated:true,sections:[{theme:"The pipeline",body:"Noon: dual UAE-Saudi listing within 24 months at ~$10B valuation. Careem: EBITDA positive FY2025, IPO on ADX or DFM possible by late 2026. Ninja: $1B Tadawul IPO in late 2026 or early 2027 with Goldman Sachs, Citi, Riyad Capital, UBS mandated. Mr Mandoob: Nomu listing after $213M+ valuation."},{theme:"Amazon implication",body:"Public listings by regional competitors create new accountability and capital availability. Noon at $10B valuation is better capitalised to compete on logistics investment. The landscape Amazon competes in by 2027 will include several well-capitalised public companies with regional roots."}],sources:[{name:"Enterprise AM",tier:2,url:"https://enterpriseam.com/menaplus/2026/05/13/saudi-firms-are-lining-up-to-ipo-while-uae-and-egyptian-outfits-strike-more-cautious-notes/",date:"13 May 2026",paywall:false}]},
      {id:"q3",category:"Market Data",categoryColor:"#0891b2",headline:"Saudi e-commerce: $21.3B in 2024, growing to $56.6B by 2032 — electronic payments hit 79% of retail",markets:["KSA"],competitor:null,corroborated:true,sections:[{theme:"Market size",body:"Saudi Arabia's e-commerce market was valued at $21.3B in 2024, projected to reach $56.6B by 2032 at 13% CAGR. Electronic payments accounted for 79% of all retail transactions in 2024, significantly exceeding the 70% target set for 2025 under the Financial Sector Development Programme."},{theme:"Payments layer",body:"SAMA launched Google Pay and agreed to accept Alipay+ by 2026, embedding international wallets into the local payments stack. This directly expands the addressable checkout infrastructure for Amazon Pay, Tabby, and Tamara simultaneously."}],sources:[{name:"Verified Market Research",tier:2,url:"https://www.verifiedmarketresearch.com/product/saudi-arabia-e-commerce-market/",date:"Oct 2025",paywall:false}]},
      {id:"q4",category:"Emerging Markets",categoryColor:"#059669",headline:"Turkey and South Africa: competitive perimeter expanding into MEATR",markets:["Turkey","South Africa","Egypt"],competitor:"Trendyol",corroborated:true,sections:[{theme:"Turkey: Trendyol's Gulf commitment",body:"Trendyol has exceeded $1B GMV in the Gulf with daily orders of 200,000 across UAE and KSA. CEO targets 50% international revenue before IPO. The company signed a fintech MoU with Abu Dhabi's ADQ and announced a $500M data centre in Ankara due Q3 2026."},{theme:"South Africa: Takealot under pressure",body:"Takealot opened its marketplace to Chinese sellers to counter Temu and Shein on price. Last reported revenue R14.95B ($872M), up 15%, but barely profitable. Management targets breakeven by 2026. Jumia reported 34% revenue growth in Q4 2025 and is advancing toward EBITDA breakeven."}],sources:[{name:"The National",tier:1,url:"https://www.thenationalnews.com/future/technology/2024/10/16/trendyol-launches-turkeys-first-llm-and-accelerates-expansion-in-the-gulf/",date:"Oct 2024",paywall:false}]},
    ]},
};

const MARKETS_LIST = [
  {id:"all",label:"All Markets"},
  {id:"gcc",label:"GCC",markets:["UAE","KSA"]},
  {id:"mea",label:"MEA",markets:["UAE","KSA","Egypt","South Africa"]},
  {id:"meatr",label:"MEATR",markets:["UAE","KSA","Egypt","South Africa","Turkey"]},
  {id:"uae",label:"UAE",markets:["UAE"]},
  {id:"ksa",label:"KSA",markets:["KSA"]},
  {id:"egypt",label:"Egypt",markets:["Egypt"]},
  {id:"turkey",label:"Turkey",markets:["Turkey"]},
  {id:"southafrica",label:"South Africa",markets:["South Africa"]},
];
